### ISSUE TITLE
r

### ISSUE THREAD

**Issue by MartinMystikJonas** [hackenbruder/govdata-js#2]
Chtěli jsme u našeho projektu použít govdata.cz pro načtení dat z ARES, ale při integraci jsme narazili na problém s tím, že requesty jsou odmítány kvůli CORS ochraně v prohlížečích.

`Failed to load https://api.govdata.cz/v1/prod/entity/: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin '***' is therefore not allowed access.`

Při použití na localhost (Origin: null) vše funguje, ale při použití na webu, kde v Origin je doména projektu dojde k tomu, že OPTIONS request na https://api.govdata.cz/v1/prod/entity/ vrátí 403.

Děláme něco špatně?

**Comment by hackenbruder** [comment]
Dobrý den,
děkujeme za zájem o naší službu a za váš technický dotaz.

Naklonujte is náš repozitář
https://github.com/hackenbruder/govdata-js

Otevřete soubor "test/index.html"
Váš prohlížeč spustí sadu testů naší javascriptové knihovny.

Následně můžete v inspektoru prozkoumat požadavky (ze sekce "GovData Integration"), nebo upravit kód inicializující javascriptovou knihovnu GovData a přidat svůj klíč a nastavení.

Podle toho, co jste uvedl v mailu se zdá, že používáte špatný endpoint (chybí vám ico subjektu)
https://api.govdata.cz/v1/prod/entity/00006947 neboli https://api.govdata.cz/v1/prod/entity/<ico subjektu>
